"""migrate

Revision ID: 8e6b50352caf
Revises: 
Create Date: 2024-04-07 13:24:01.277144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6b50352caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=500), nullable=True))

    with op.batch_alter_table('uptodate_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptodate_news', schema=None) as batch_op:
        batch_op.drop_column('channel')
        batch_op.drop_column('section')
        batch_op.drop_column('country')
        batch_op.drop_column('state')

    with op.batch_alter_table('all_news', schema=None) as batch_op:
        batch_op.drop_column('channel')
        batch_op.drop_column('section')
        batch_op.drop_column('country')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
